Technics
tania833/Barvy pull request #11
Opened 2020-11-23 18:21 UTC by Towko

2020-11-23 20:42 UTC, tania833 requested changes

2020-11-23 20:42 UTC, tania833 commented on barvy/src/App.css
>    src: url("/src/fonts/Montserrat-Medium.ttf");
Please do not leave commits. If you want to delete something unnecessary- just do it :)

2020-11-23 20:42 UTC, tania833 commented on barvy/src/components/TechCard.jsx
> +    return <div className={styles.courseCard__wrapper}>{courseCardInfo}</div>;
Cool

2020-11-23 20:42 UTC, tania833 commented on barvy/src/fonts/stylesheet.css
> +
Empty lines

2020-11-23 20:42 UTC, tania833 commented on barvy/src/fonts/stylesheet.css
> +
Empty lines

2020-11-23 20:42 UTC, tania833 commented on barvy/src/fonts/stylesheet.css
> +
Empty lines

2020-11-23 20:42 UTC, tania833 commented on barvy/src/fonts/stylesheet.css
> +
Empty lines

2020-11-23 20:42 UTC, tania833 commented on barvy/src/fonts/stylesheet.css
> +
Empty lines

2020-11-23 20:42 UTC, tania833 commented on barvy/src/pages/Main/components/Technologies/Technologies.jsx
> +// import TechCard from './../../../../components/TechCard';
Do not leave comments

2020-11-23 20:42 UTC, tania833 commented on barvy/src/pages/Main/components/Technologies/Technologies.jsx
> +            {/* <TechCard techPic={TechCard} /> */}
Comments

2020-11-23 20:42 UTC, tania833 commented on barvy/src/pages/Main/components/Technologies/Technologies.module.scss
> +        // width: 28.125rem;
Comments

2020-11-23 20:42 UTC, tania833 commented on barvy/src/pages/Main/components/WannaTry/WannaTry.jsx
> +    <div className={styles.WannaTry}>
Cool

2020-11-24 13:20 UTC, Towko commented on barvy/src/App.css
>    src: url("/src/fonts/Montserrat-Medium.ttf");
OK! But I wanted deleted it later, for testing after merging

2020-11-24 13:26 UTC, Towko commented on barvy/src/components/TechCard.jsx
> +    return <div className={styles.courseCard__wrapper}>{courseCardInfo}</div>;
no-no! Propses is just not yet ready, for now it unfinished and this file is not used yet

2020-11-24 13:26 UTC, Towko commented on barvy/src/fonts/stylesheet.css
> +
This file is generated by font converter automatically. It's not me. But, this file unused and can be deleted. I do it in the next upd

2020-11-24 13:26 UTC, Towko commented on barvy/src/pages/Main/components/Technologies/Technologies.jsx
> +// import TechCard from './../../../../components/TechCard';
before production I'll cleaning all. But it comment for me now, because it's not finished. I want to do it with propses

2020-11-24 13:26 UTC, Towko commented on barvy/src/pages/Main/components/Technologies/Technologies.jsx
> +            {/* <TechCard techPic={TechCard} /> */}
O_o

2020-11-24 13:26 UTC, Towko commented on barvy/src/pages/Main/components/Technologies/Technologies.module.scss
> +        // width: 28.125rem;
aaarrrrrggggghhhh...

2020-11-24 13:26 UTC, Towko commented on barvy/src/pages/Main/components/WannaTry/WannaTry.jsx
> +    <div className={styles.WannaTry}>
thanx

2020-11-24 13:29 UTC, tania833 commented on barvy/src/fonts/stylesheet.css
> +
Great

2020-11-24 15:32 UTC, tania833 approved these changes

2020-11-24 15:32 UTC, merged