first part without img
tania833/Barvy pull request #5
Opened 2020-11-22 09:33 UTC by SvitlanaKalmutska

2020-11-22 09:42 UTC, tania833 requested changes

2020-11-22 09:42 UTC, tania833 commented on barvy/src/pages/Main/css.modules/HowItWorks.module.scss
> +    // &__icon img {
Не лишай, будь ласка, коментів. Якщо не потрібне - видаляй

2020-11-22 09:42 UTC, tania833 commented on barvy/src/pages/Main/css.modules/HowItWorks.module.scss
> +        font-size: 18px;
Все в ремах, а тут px

2020-11-22 09:42 UTC, tania833 commented on barvy/src/pages/Main/css.modules/HowItWorks.module.scss
> +        font-family: Montserrat;
Ми шрифти в лапки не беремо? Чи  і так відображається?

2020-11-22 11:34 UTC, SvitlanaKalmutska commented on barvy/src/pages/Main/css.modules/HowItWorks.module.scss
> +        font-family: Montserrat;
Працює і так. Таня не брала, я з неї приклад взяла)

2020-11-22 11:36 UTC, SvitlanaKalmutska commented on barvy/src/pages/Main/css.modules/HowItWorks.module.scss
> +    // &__icon img {
Блін, я трохи, певно, таки зарано змержила. Бо ще багато доробляти треба. Тобто це ж далеко не остаточний варіант. Тому і купа закоментованого усього ще

2020-11-22 11:37 UTC, SvitlanaKalmutska commented on barvy/src/pages/Main/css.modules/HowItWorks.module.scss
> +        font-size: 18px;
ага, виправлю, дякую, не помітила вчора вже

2020-11-23 20:49 UTC, tania833 commented on barvy/src/pages/Main/css.modules/HowItWorks.module.scss
> +        font-family: Montserrat;
Cool!

2020-11-24 09:22 UTC, tania833 approved these changes

2020-11-24 18:06 UTC, merged